[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["chry wsl <chenruiyun@3wlink.cn>"]
edition = "2018"

# 声明 hello_macro_derive crate 是过程宏(proc-macro) crate
[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"


